package entidades;
// Generated 14/07/2019 06:13:44 PM by Hibernate Tools 4.3.1



/**
 * AtencionId generated by hbm2java
 */
public class AtencionId  implements java.io.Serializable {


     private int idAtencion;
     private int personalIdPersonal;

    public AtencionId() {
    }

    public AtencionId(int idAtencion, int personalIdPersonal) {
       this.idAtencion = idAtencion;
       this.personalIdPersonal = personalIdPersonal;
    }
   
    public int getIdAtencion() {
        return this.idAtencion;
    }
    
    public void setIdAtencion(int idAtencion) {
        this.idAtencion = idAtencion;
    }
    public int getPersonalIdPersonal() {
        return this.personalIdPersonal;
    }
    
    public void setPersonalIdPersonal(int personalIdPersonal) {
        this.personalIdPersonal = personalIdPersonal;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AtencionId) ) return false;
		 AtencionId castOther = ( AtencionId ) other; 
         
		 return (this.getIdAtencion()==castOther.getIdAtencion())
 && (this.getPersonalIdPersonal()==castOther.getPersonalIdPersonal());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdAtencion();
         result = 37 * result + this.getPersonalIdPersonal();
         return result;
   }   


}


