package entidades;
// Generated 14/07/2019 06:13:44 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private int idCliente;
     private String nombre;
     private String apellido;
     private Date fechaNacimiento;
     private String direccion;
     private String numeroTelefonico;
     private String email;
     private Set clientepormascotas = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(int idCliente, String nombre, String apellido, Date fechaNacimiento, String direccion, String numeroTelefonico, String email) {
        this.idCliente = idCliente;
        this.nombre = nombre;
        this.apellido = apellido;
        this.fechaNacimiento = fechaNacimiento;
        this.direccion = direccion;
        this.numeroTelefonico = numeroTelefonico;
        this.email = email;
    }
    public Cliente(int idCliente, String nombre, String apellido, Date fechaNacimiento, String direccion, String numeroTelefonico, String email, Set clientepormascotas) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.apellido = apellido;
       this.fechaNacimiento = fechaNacimiento;
       this.direccion = direccion;
       this.numeroTelefonico = numeroTelefonico;
       this.email = email;
       this.clientepormascotas = clientepormascotas;
    }
   
    public int getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(int idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getNumeroTelefonico() {
        return this.numeroTelefonico;
    }
    
    public void setNumeroTelefonico(String numeroTelefonico) {
        this.numeroTelefonico = numeroTelefonico;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getClientepormascotas() {
        return this.clientepormascotas;
    }
    
    public void setClientepormascotas(Set clientepormascotas) {
        this.clientepormascotas = clientepormascotas;
    }




}


